spring:
log4j:
  logger:
    httpclient:
      wire: DEBUG
      
logging:
  level:
    org.springframework.web: DEBUG
    


server:
  port : 4002
  
apiservice:
  host: localhost
  port: 4000  




management:
  endpoints:
    web:
      exposure:
        include: "*" 
  endpoint:
    health:
      show-details: always     
        




